# Development profile configuration
# This can be used for local development with Azure PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://mydb.postgres.database.azure.com:5432/mydatabase?sslmode=require
    username: myuser@mydb
    password: your_password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
