# Docker Compose file - PostgreSQL service removed
# Now using Azure Database for PostgreSQL
# To use local PostgreSQL for development, uncomment the service below:
#
# services:
#   postgres:
#     image: 'postgres:latest'
#     environment:
#       - 'POSTGRES_DB=mydatabase'
#       - 'POSTGRES_PASSWORD=secret'
#       - 'POSTGRES_USER=myuser'
#     ports:
#       - '5432:5432'
